flows:
  - type: playground
    id: RETINVL_DISCOVERY_FLOW
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Discovery Flow for Inventory Less (Buy now journey and find best price)
    config:
      $ref: "src/config/RETINVL/v-1.2.5/RETINVL/flows/RETINVL_DISCOVERY_FLOW.yaml"
  - type: playground
    id: ORDER_FLOW_BASELINE
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Order Flow Baseline for Inventory Less (Buy now journey and find best price)
    config:
      $ref: "src/config/RETINVL/v-1.2.5/RETINVL/flows/ORDER_FLOW_BASELINE.yaml"